### ISSUE TITLE
some question about the PSNR evaluation

### ISSUE THREAD

**Issue by LiXinghui-666** [primecai/Pix2NeRF#15]
Thank you for your work! I'd like to ask how the PSNR of the srnchairs part of the paper compares. Because the pose angle defined in the code is different from the actual distribution in the data set, how do you compare the PSNR values of the rendered new view images? If it's convenient, could you provide code or some suggestions to me. Thanks!

**Comment by primecai** [comment]
Hi,

Pix2NeRF has an encoder that predicts a latent code z and its pose d from an image. Therefore, we simply use the encoder on the novel views to get their poses, rather than using the ground truth poses. This evaluation detail is mentioned in part 4.2 Quantitative Results section of our paper.
Doing this is of course, not very accurate. As you can see, our PSNR results are not that impressive—a large portion of the error comes from the inaccurately predicted poses.

Best regards,
Shengqu
